### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by IchordeDionysos** [hoc081098/sqlbrite#3]
This is a request to add support for [null safety](https://dart.dev/null-safety) to `package:sqlbrite`.
We depend on your awesome package, so would be great to have null safety enabled.

The Dart/Flutter team already encourages publishing the migrated packages: See [this blog post](https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010).

See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

**Comment by hoc081098** [comment]
Thanks @IchordeDionysos, I am going to update it

**Comment by hoc081098** [comment]
I have published it: https://pub.dev/packages/sqlbrite/versions/2.0.0-nullsafety.0

**Comment by IchordeDionysos** [comment]
@hoc081098 any plans to release a stable version with null-safety? ☺️ 
It's been a month now since the null-safe pre-release version

**Comment by hoc081098** [comment]
@IchordeDionysos I'm going to publish it today 😂

_Sent from my Redmi  7A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
