### ISSUE TITLE
'BriteBatch' is missing implementation for Batch.apply

### ISSUE THREAD

**Issue by vmalyi** [hoc081098/sqlbrite#37]
Hey there,

with an update to Flutter 3.3.2, my app's build suddenly start to fail with the following message:

```
Error: The non-abstract class 'BriteBatch' is missing implementations for these members:
../…/src/brite_batch.dart:8
     - Batch.apply

class BriteBatch implements IBriteBatch {
          ^^^^^^^^^^
: Context: 'Batch.apply' is defined here.
../…/lib/sqlite_api.dart:479
      Future<List<Object?>> apply({bool? noResult, bool? continueOnError});
                            ^^^^^
```

The `sqlbrite` version I'm using is` 2.3.0`.

After checking the `sqlbrite-2.3.0/lib/src/brite_batch.dart` I found out that the implementation of `Future<List<Object?>> apply({bool? noResult, bool? continueOnError})` is indeed missing and this causes the issue.

Any chance this can be addressed?

Thanks in advance!

**Comment by hoc081098** [comment]
Hey @vmalyi, https://pub.dev/packages/sqlbrite/versions/2.4.0 is out. Give it a try 👍
