### ISSUE TITLE
Error: The non-abstract class 'BriteDatabase' is missing implementations for these members

### ISSUE THREAD

**Issue by dargod** [hoc081098/sqlbrite#41]
Launching lib/main.dart on moto g22 in debug mode...
: Error: The non-abstract class 'BriteTransaction' is missing implementations for these members:
 - DatabaseExecutor.queryCursor

 - DatabaseExecutor.rawQueryCursor
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class BriteTransaction extends AbstractBriteDatabaseExecutor
      ^^^^^^^^^^^^^^^^
: Context: 'DatabaseExecutor.queryCursor' is defined here.
  Future<QueryCursor> queryCursor(String table,
                      ^^^^^^^^^^^
: Context: 'DatabaseExecutor.rawQueryCursor' is defined here.
  Future<QueryCursor> rawQueryCursor(String sql, List<Object?>? arguments,
                      ^^^^^^^^^^^^^^
: Error: The non-abstract class 'BriteDatabase' is missing implementations for these members:
 - DatabaseExecutor.queryCursor

 - DatabaseExecutor.rawQueryCursor
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class BriteDatabase extends AbstractBriteDatabaseExecutor
      ^^^^^^^^^^^^^
: Context: 'DatabaseExecutor.queryCursor' is defined here.
  Future<QueryCursor> queryCursor(String table,
                      ^^^^^^^^^^^
: Context: 'DatabaseExecutor.rawQueryCursor' is defined here.
  Future<QueryCursor> rawQueryCursor(String sql, List<Object?>? arguments,

                      ^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script '/Users/darek/Desktop/Dev/Flutter/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/darek/Desktop/Dev/Flutter/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Exception: Gradle task assembleDebug failed with exit code 1
Exited

**Comment by dargod** [comment]
This happens since updating to Flutter 3.3.6

[✓] Flutter (Channel stable, 3.3.6, on macOS 12.6 21G115 darwin-x64, locale en-PL)
    • Flutter version 3.3.6 on channel stable at /Users/darek/Desktop/Dev/Flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (5 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

**Comment by hoc081098** [comment]
@dargod https://pub.dev/packages/sqlbrite/versions/2.5.0 is out. Give it a try

**Comment by dargod** [comment]
@hoc081098 thank you for quick fix. It's all working fine now with v2.5.0

**Comment by hoc081098** [comment]
I'm glad to hear that
