### ISSUE TITLE
Missing concrete implementation of 'getter Batch.length'.

### ISSUE THREAD

**Issue by vmalyi** [hoc081098/sqlbrite#44]
See [here](https://pub.dev/packages/sqlbrite/score).

<img width="771" alt="Bildschirmfoto 2023-01-17 um 14 01 51" src="https://user-images.githubusercontent.com/1609148/212905870-585c97e9-62d7-4d6d-a1ff-4852c0dca104.png">

**Comment by josh-burton** [comment]
I upgraded to Flutter 3.7 and am now getting this error.

**Comment by hoc081098** [comment]
hi, https://pub.dev/packages/sqlbrite/versions/2.5.1 released 👍
