### ISSUE TITLE
Flutter 3.7 Error:The non-abstract class 'BriteDatabase' is missing implementations for these members

### ISSUE THREAD

**Issue by mumenma** [hoc081098/sqlbrite#47]
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/sqlbrite-2.5.1/lib/src/brite_database.dart:17:7: Error: The non-abstract class 'BriteDatabase' is missing implementations for these members:

**Comment by hoc081098** [comment]
@mumenma please upgrade to `^2.5.1`

**Comment by mumenma** [comment]
@hoc081098 now is sqlbrite-2.5.1

**Comment by mumenma** [comment]
../../../.pub-cache/hosted/pub.dev/sqlbrite-2.5.1/lib/src/brite_database.dart:17:7: Error: The non-abstract class 'BriteDatabase' is missing implementations for these members:
 - DatabaseExecutor.database
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class BriteDatabase extends AbstractBriteDatabaseExecutor
      ^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/sqflite_common-2.4.2+2/lib/sqlite_api.dart:260:16: Context: 'DatabaseExecutor.database' is defined here.
  Database get database;
               ^^^^^^^^
../../../.pub-cache/hosted/pub.dev/sqlbrite-2.5.1/lib/src/brite_transaction.dart:8:7: Error: The non-abstract class 'BriteTransaction' is missing implementations for these members:
 - DatabaseExecutor.database
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class BriteTransaction extends AbstractBriteDatabaseExecutor
      ^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/sqflite_common-2.4.2+2/lib/sqlite_api.dart:260:16: Context: 'DatabaseExecutor.database' is defined here.
  Database get database;
               ^^^^^^^^

**Comment by hoc081098** [comment]
@mumenma please use https://pub.dev/packages/sqlbrite/versions/2.6.0
