### ISSUE TITLE
Error: error: ../../../../.pub-cache/hosted/pub.dev/sqlbrite-2.6.0/lib/src/brite_database.dart:17:7: Error: The non-abstract class 'BriteDatabase' is missing implementations for these members:

### ISSUE THREAD

**Issue by dargod** [hoc081098/sqlbrite#54]
Hello,

This used to be an issue couple months ago when building locally but it was fixed. Now I am getting similar error when using Github Action. I am puzzled of what it might be.

![image](https://github.com/hoc081098/sqlbrite/assets/5755810/6b58b9c6-60ba-4c6a-a66d-3d39cff76091)

I can't expand to see what those members are.

I have even specified exact versions to use in pubspec.yaml

sqlbrite: 2.6.0
sqflite: 2.2.4

**Comment by dargod** [comment]
I have run flutter test and here is the output.

../../../../.pub-cache/hosted/pub.dev/sqlbrite-2.6.0/lib/src/brite_database.dart:17:7: Error: The non-abstract class 'BriteDatabase' is missing implementations for these members:
 - Database.readTransaction
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.
class BriteDatabase extends AbstractBriteDatabaseExecutor
      ^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/sqflite_common-2.5.3/lib/sqlite_api.dart:300:13: Context: 'Database.readTransaction' is defined here.
  Future<T> readTransaction<T>(Future<T> Function(Transaction txn) action);
            ^^^^^^^^^^^^^^^

**Comment by hoc081098** [comment]
Hi @dargod,
Thanks for your report, I will fix it ASAP 🙏

**Comment by hoc081098** [comment]
@dargod , please give https://pub.dev/packages/sqlbrite/versions/2.7.0 a try 🌸
