### ISSUE TITLE
Will it work with transactions?

### ISSUE THREAD

**Issue by rasuru** [hoc081098/sqlbrite#8]
I am trying to insert from transaction, in which case the stream does not get notified. Any plans on supporting this?

**Comment by rasuru** [comment]
Also, did not work with rawDelete. Is it not supported or is it a bug?

**Comment by hoc081098** [comment]
Hi @rasuru using rawDeleteAndTrigger instead

_Sent from my Redmi  7A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hoc081098** [comment]
@rasuru also, `transactionAndTrigger` 😂

_Sent from my Redmi  7A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rasuru** [comment]
Sorry, I assume this is documented and I should have read better ^^"
